apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kwyre-secrets
type: Opaque
stringData:
  api-keys: {{ .Values.secrets.apiKeys | quote }}
  {{- if .Values.secrets.masterKey }}
  master-key: {{ .Values.secrets.masterKey | quote }}
  {{- end }}
  {{- if .Values.secrets.licenseKey }}
  license-key: {{ .Values.secrets.licenseKey | quote }}
  {{- end }}
